<a href="https://colab.research.google.com/github/19PA1A0249/AI-LAB/blob/master/AIEXPERIMENT_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

K SAILESH ; 19PA1A0249 ; EEE-A ; II-I ; AI - Lab experiment 1


1) Different ways to create Numpy arrays 

In [ ]:
import numpy as np
a = np.array([4,6,7,8,3,5])
print(a)

[4 6 7 8 3 5]


In [ ]:
a = np.array([[6,8,9],[3,4,6]])
print(a)

[[6 8 9]
 [3 4 6]]


2) Add  ,remove  ,modify elements in an array

In [ ]:
import numpy as np
a = np.arange(15)
b = np.append(a,[15,17])
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 17]


In [ ]:
c = np.delete(a,[9])
print(c)

[ 0  1  2  3  4  5  6  7  8 10 11 12 13 14]


In [ ]:
d = np.array([1,4,4,6,3,9,5,8])
d[d<2]=-9
print(d)

[-9  4  4  6  3  9  5  8]


3) Arthematic operations on Numpy array

In [ ]:
import numpy as np
e = np.array([[6,5,8],[4,8,4]])
f = np.array([[2,2,2],[3,3,4]])
sum = np.add(e,f)
diff = np.subtract(e,f)
prod = np.multiply(e,f)
quo = np.divide(e,f)
mod = np.mod(e,f)
pow = np.power(e,f)
print(sum)
print(diff)
print(prod)
print(quo)
print(mod)
print(pow)

[[ 8  7 10]
 [ 7 11  8]]
[[4 3 6]
 [1 5 0]]
[[12 10 16]
 [12 24 16]]
[[3.         2.5        4.        ]
 [1.33333333 2.66666667 1.        ]]
[[0 1 0]
 [1 2 0]]
[[ 36  25  64]
 [ 64 512 256]]


4)Slicing and iterating of numpy arrays


a) Slicing

In [ ]:
import numpy as np
g = np.array([4,4,3,7,8,3,5,1,9,0])
print(g[3:9])

[7 8 3 5 1 9]


b)Iterating

In [ ]:
for i in g:
 print(i)

4
4
3
7
8
3
5
1
9
0


5)Matrix operations on numpy arrays

In [ ]:
import numpy as np
h = np.array([[5,9,2],[8,5,6]])
i = np.array([[1,2,1],[1,7,1]])
print(np.add(h,i))
print(np.subtract(h,i))
print(np.divide(h,i))

[[ 6 11  3]
 [ 9 12  7]]
[[ 4  7  1]
 [ 7 -2  5]]
[[5.         4.5        2.        ]
 [8.         0.71428571 6.        ]]
